name: landmark_unet
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.2.1=h06a4308_0
  - certifi=2021.10.8=py39h06a4308_2
  - cudatoolkit=10.2.89=hfd86e86_1
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9d=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1m=h7f8727e_0
  - pillow=9.0.1=py39h22f2fdc_0
  - pip=21.2.4=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.37.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021e=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - ffmpeg=4.3=hf484d3e_0
  - pytorch=1.10.2=py3.9_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - torchaudio=0.10.2=py39_cu102
  - torchvision=0.11.3=py39_cu102
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - albumentations==1.1.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - comet-ml==3.28.0
    - configobj==5.0.6
    - cycler==0.11.0
    - dominate==2.6.0
    - dulwich==0.20.33
    - et-xmlfile==1.1.0
    - everett==3.0.0
    - fonttools==4.29.1
    - frozenlist==1.3.0
    - fsspec==2022.2.0
    - future==0.18.2
    - glob2==0.7
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - idna==3.3
    - imageio==2.16.1
    - imgaug==0.4.0
    - importlib-metadata==4.11.2
    - joblib==1.1.0
    - jsonschema==4.4.0
    - kiwisolver==1.3.2
    - markdown==3.3.6
    - matplotlib==3.5.1
    - multidict==6.0.2
    - networkx==2.7.1
    - nibabel==3.2.2
    - nose==1.3.7
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.2.0
    - opencv-python==4.5.5.64
    - opencv-python-headless==4.5.5.62
    - openpyxl==3.0.9
    - packaging==21.3
    - pandas==1.4.1
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pydicom==2.3.0
    - pykale==0.1.1
    - pylibjpeg==1.4.0
    - pylibjpeg-libjpeg==1.3.1
    - pylibjpeg-openjpeg==1.2.1
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-gdcm==3.0.17.1
    - pytorch-lightning==1.5.10
    - pytz==2022.1
    - pywavelets==1.2.0
    - pyyaml==6.0
    - qudida==0.0.4
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - requests-toolbelt==0.9.1
    - rsa==4.8
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - semantic-version==2.9.0
    - shapely==1.8.1.post1
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorly==0.7.0
    - threadpoolctl==3.1.0
    - tifffile==2022.2.9
    - torch==1.12.1
    - torchmetrics==0.7.2
    - tqdm==4.63.0
    - urllib3==1.26.8
    - websocket-client==1.3.1
    - werkzeug==2.0.3
    - wrapt==1.14.0
    - wurlitzer==3.0.2
    - yacs==0.1.8
    - yarl==1.7.2
    - zipp==3.7.0
prefix: /home/acq19las/.conda/envs/landmark_unet

